# Generated by Django 4.2.7 on 2023-11-03 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_rename_region_address_city'),
        ('comments', '0002_review_delete_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(default=None, max_length=5000, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 19, 37, 25, 423821)),
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='review',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 19, 37, 25, 423821)),
        ),
    ]
