# Generated by Django 4.2.3 on 2023-10-30 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Цена не может быть меньше 0'), django.core.validators.MaxValueValidator(10000, 'Цена не может быть больше 10000')], verbose_name='Цена тура'),
        ),
    ]
