# Generated by Django 4.2.3 on 2023-11-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_rename_img_tour_photo_remove_tour_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='region',
            new_name='city',
        ),
    ]
